replicaCount: 10
    # Example: Use tolerations to allow scheduling on tainted nodes
    # tolerations:
    # - key: "high-performance"
    #   operator: "Equal"
    #   value: "true"
    #   effect: "NoSchedule"
    # # Can also override multiple settings together
    # nodeSelector:
    #   instance-type: "high-memory"
