apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "busybox-chart.labels" $ | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "busybox-chart.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "busybox-chart.labels" $ | nindent 8 }}
    spec:
      containers:
        - name: busybox
          image: "448435121187.dkr.ecr.us-east-1.amazonaws.com/busybox:1.31.1-multiarch"
          imagePullPolicy: IfNotPresent
          command: ["tail", "-f", "/dev/null"]
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - "pgrep tail || exit 1"
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - "ps aux | grep 'tail -f /dev/null' | grep -v grep"
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 1
            successThreshold: 1
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: DEPLOYMENT_NAME
              value: {{ .Release.Name }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- .Values.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- .Values.affinity | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- .Values.tolerations | toYaml | nindent 8 }}
      {{- end }}
