{{- range .Values.multiNamespace.namespaces }}
{{- $namespace := .name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "busybox-chart.namespacedName" (dict "namespace" $namespace "root" $) }}
  namespace: {{ $namespace }}
  labels:
    {{- include "busybox-chart.labels" $ | nindent 4 }}
    busybox-chart.namespace: {{ $namespace }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "busybox-chart.selectorLabels" $ | nindent 4 }}
    busybox-chart.namespace: {{ $namespace }}
{{- end }}