apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "busybox-chart.labels" $ | nindent 4 }}
    busybox-chart.namespace: {{ .Release.Namespace }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "busybox-chart.selectorLabels" $ | nindent 4 }}
    busybox-chart.namespace: {{ .Release.Namespace }}
